<?php

use Drupal\Core\Form\FormStateInterface;

require_once __DIR__ . '/includes/server_configurator.callbacks.inc';

/**
 * @file
 * Main module file for Server Configurator module.
 */

/**
 * Implements hook_page_attachments().
 */
function server_configurator_page_attachments(array &$attachments) {
  \Drupal::service('server_configurator.bootstrap_manager')
    ->attachToPage($attachments);
}

/**
 * Implements hook_hook_info().
 */
function server_configurator_hook_info() {
  $hooks = [];

  $hooks['token_info'] = [
    'group' => 'token',
  ];

  $hooks['tokens'] = [
    'group' => 'token',
  ];

  return $hooks;
}

/**
 * Implements hook_form_alter().
 */
function server_configurator_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  \Drupal::service('server_configurator.form_alter_router')
    ->alter($form, $form_state, $form_id);
}
