_core:
  default_config_hash: 4GIX5Esnc_umpXUBj4IIocRX7Mt5fPhm4AgXfE3E56E
module:
  action: 0
  addtoany: 0
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  announcements_feed: 0
  antibot: 0
  asset_injector: 0
  automated_cron: 0
  back_to_top: 0
  basic_auth: 0
  better_exposed_filters: 0
  big_pipe: 0
  blazy: 0
  block: 0
  block_content: 0
  block_field: 0
  bootstrap_layout_builder: 0
  bootstrap_styles: 0
  bpmn_io: 0
  breakpoint: 0
  ckeditor5: 0
  comment: 0
  conditional_fields: 0
  config: 0
  config_translation: 0
  config_update: 0
  contact: 0
  content_audit: 0
  content_entity_clone: 0
  contextual: 0
  cookies: 0
  cshs: 0
  csv_serialization: 0
  ctools: 0
  datafield: 0
  datetime: 0
  dbal: 0
  dblog: 0
  dropzonejs: 0
  dual_range_slider: 0
  dynamic_page_cache: 0
  ebt_accordion: 0
  ebt_core: 0
  ebt_core_starterkit: 0
  ebt_slick_slider: 0
  ebt_tabs: 0
  ebt_text: 0
  eca: 0
  eca_base: 0
  eca_config: 0
  eca_content: 0
  eca_modeller_bpmn: 0
  eca_queue: 0
  eca_render: 0
  eca_tamper: 0
  eca_tg: 0
  eca_ui: 0
  eca_user: 0
  eca_views: 0
  eca_webform: 0
  editablefields: 0
  editor: 0
  elevatezoomplus: 0
  elevatezoomplus_ui: 0
  entity: 0
  entity_browser: 0
  entity_clone: 0
  entity_hierarchy: 0
  entity_print: 0
  entity_reference_revisions: 0
  erd: 0
  eva: 0
  exclude_node_title: 0
  features: 0
  features_ui: 0
  feeds: 0
  feeds_log: 0
  feeds_tamper: 0
  field: 0
  field_collection: 0
  field_formatter: 0
  field_group: 0
  field_group_migrate: 0
  field_token_value: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  file_mdm_exif: 0
  file_mdm_font: 0
  filter: 0
  glightbox: 0
  glightbox_media_video: 0
  hal: 0
  help: 0
  history: 0
  honeypot: 0
  hook_event_dispatcher: 0
  image: 0
  image_effects: 0
  image_url_formatter: 0
  inline_entity_form: 0
  ipless: 0
  jquery_ui: 0
  jquery_ui_accordion: 0
  jquery_ui_autocomplete: 0
  jquery_ui_menu: 0
  jquery_ui_resizable: 0
  jquery_ui_slider: 0
  jquery_ui_tabs: 0
  jsonapi: 0
  language: 0
  layout_builder: 0
  layout_builder_blocks: 0
  layout_builder_component_attributes: 0
  layout_discovery: 0
  libraries: 0
  link: 0
  locale: 0
  mailer_transport: 0
  media: 0
  media_bulk_upload: 0
  media_bulk_upload_dropzonejs: 0
  media_entity_slideshow: 0
  media_library: 0
  media_library_form_element: 0
  media_migration: 0
  media_migration_tools: 0
  media_pdf_thumbnail: 0
  menu_breadcrumb: 0
  menu_item_extras: 0
  menu_link_attributes: 0
  menu_link_content: 0
  menu_ui: 0
  menus_attribute: 0
  metatag: 0
  metatag_dc: 0
  metatag_dc_advanced: 0
  metatag_mobile: 0
  metatag_verification: 0
  metatag_views: 0
  migmag: 0
  migmag_menu_link_migrate: 0
  migmag_process: 0
  migrate: 0
  migrate_drupal: 0
  migrate_drupal_ui: 0
  migrate_file: 0
  migrate_plus: 0
  migrate_skip_fields: 0
  migrate_tools: 0
  migrate_upgrade: 0
  migrate_url2link: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  pdf_preview_image: 0
  phpass: 0
  profile: 0
  protected_forms: 0
  quick_node_clone: 0
  quicktabs: 0
  quicktabs_jqueryui: 0
  range_slider: 0
  redirect: 0
  redirect_404: 0
  rest: 0
  restui: 0
  scanner: 0
  schema_metatag: 0
  sdc: 0
  search: 0
  section_library: 0
  serialization: 0
  server_configurator: 0
  shortcode: 0
  shortcut: 0
  simple_sitemap: 0
  single_content_sync: 0
  slick: 0
  slick_extras: 0
  slick_lightbox: 0
  slick_ui: 0
  slick_views: 0
  smart_sql_idmap: 0
  symfony_mailer: 0
  symfony_mailer_log: 0
  system: 0
  tamper: 0
  taxonomy: 0
  taxonomy_import: 0
  taxonomy_manager: 0
  telephone: 0
  telephone_validation: 0
  text: 0
  token: 0
  token_custom: 0
  token_filter: 0
  token_or: 0
  token_or_webform: 0
  token_views_filter: 0
  toolbar: 0
  twig_tweak: 0
  type_tray: 0
  update: 0
  upgrade_status: 0
  user: 0
  verf: 0
  views_argument_token: 0
  views_bulk_edit: 0
  views_bulk_operations: 0
  views_contextual_filters_or: 0
  views_data_export: 0
  views_dependent_filters: 0
  views_exposed_range_slider: 0
  views_infinite_scroll: 0
  views_migration: 0
  views_selective_filters: 0
  views_slideshow: 0
  views_slideshow_cycle: 0
  views_ui: 0
  viewsreference: 0
  webform: 0
  webform_ajax_element: 0
  webform_entity_view: 0
  webform_hierarchy: 0
  webform_migrate: 0
  webform_node: 0
  webform_nouislider: 0
  webform_ui: 0
  webform_views: 0
  yandex_maps: 0
  yandex_maps_examples: 0
  yoast_seo: 0
  ds: 1
  eca_form: 1
  pathauto: 1
  selective_better_exposed_filters: 1
  webform_bootstrap: 1
  ds_extras: 2
  cshs_menu_link: 5
  views: 10
  contextual_range_filter: 11
  paragraphs: 11
  standard: 1000
theme:
  olivero: 0
  claro: 0
  stable9: 0
  radix: 0
  tiscom_radix: 0
  bootstrap5: 0
profile: standard
