_core:
  default_config_hash: tZBqRctRg3fdrKB6LcLAmuNHmveOvaLmbIqRhaKTrBE
word_boundaries: auto
scanner_mode: true
scanner_wholeword: true
scanner_regex: false
scanner_published: false
scanner_pathauto: false
scanner_language: all
enabled_content_types:
  'node:advertisment': 'node:advertisment'
  'node:arcsystem': 'node:arcsystem'
  'node:article': 'node:article'
  'node:blade_components': 'node:blade_components'
  'node:certificate': 'node:certificate'
  'node:computer': 'node:computer'
  'node:cpu_intel': 'node:cpu_intel'
  'node:datasystem': 'node:datasystem'
  'node:dexp_portfolio': 'node:dexp_portfolio'
  'node:fpoint': 'node:fpoint'
  'node:gstation': 'node:gstation'
  'node:hcici': 'node:hcici'
  'node:intel': 'node:intel'
  'node:moduleserver_components': 'node:moduleserver_components'
  'node:news': 'node:news'
  'node:page': 'node:page'
  'node:parts': 'node:parts'
  'node:platform': 'node:platform'
  'node:processor': 'node:processor'
  'node:rack': 'node:rack'
  'node:sale': 'node:sale'
  'node:san_adapter': 'node:san_adapter'
  'node:san_controller': 'node:san_controller'
  'node:server': 'node:server'
  'node:server2': 'node:server2'
  'node:sh': 'node:sh'
  'node:software': 'node:software'
  'node:ssdsystem': 'node:ssdsystem'
  'node:superhero_portfolio': 'node:superhero_portfolio'
  'node:tis_page': 'node:tis_page'
  'node:vendor_ss': 'node:vendor_ss'
  'node:webform': 'node:webform'
  'paragraph:accordion': 'paragraph:accordion'
  'paragraph:accordion_item': 'paragraph:accordion_item'
  'paragraph:adds': 'paragraph:adds'
  'paragraph:card': 'paragraph:card'
  'paragraph:card_group': 'paragraph:card_group'
  'paragraph:carousel_item': 'paragraph:carousel_item'
  'paragraph:ebt_accordion': 'paragraph:ebt_accordion'
  'paragraph:ebt_slick_slider': 'paragraph:ebt_slick_slider'
  'paragraph:ebt_tab': 'paragraph:ebt_tab'
  'paragraph:i1': 'paragraph:i1'
  'paragraph:paragraphs_pack_content': 'paragraph:paragraphs_pack_content'
  'paragraph:paragraphs_pack_node_list': 'paragraph:paragraphs_pack_node_list'
  'paragraph:xeone5': 'paragraph:xeone5'
fields_of_selected_content_type:
  'node:arcsystem:body': 'node:arcsystem:body'
  'node:arcsystem:field_description': 'node:arcsystem:field_description'
  'node:arcsystem:field_keys': 'node:arcsystem:field_keys'
  'node:arcsystem:field_model': 'node:arcsystem:field_model'
  'node:arcsystem:field_specification': 'node:arcsystem:field_specification'
  'node:article:title': 'node:article:title'
  'node:article:body': 'node:article:body'
  'node:blade_components:title': 'node:blade_components:title'
  'node:blade_components:body': 'node:blade_components:body'
  'node:blade_components:field_description': 'node:blade_components:field_description'
  'node:blade_components:field_keys': 'node:blade_components:field_keys'
  'node:blade_components:field_specification': 'node:blade_components:field_specification'
  'node:certificate:title': 'node:certificate:title'
  'node:certificate:body': 'node:certificate:body'
  'node:certificate:field_certsystem': 'node:certificate:field_certsystem'
  'node:certificate:field_product': 'node:certificate:field_product'
  'node:certificate:field_serial': 'node:certificate:field_serial'
  'node:certificate:field_sootv': 'node:certificate:field_sootv'
  'node:computer:title': 'node:computer:title'
  'node:computer:field_description': 'node:computer:field_description'
  'node:computer:field_keys': 'node:computer:field_keys'
  'node:computer:field_specification': 'node:computer:field_specification'
  'node:moduleserver_components:title': 'node:moduleserver_components:title'
  'node:moduleserver_components:body': 'node:moduleserver_components:body'
  'node:moduleserver_components:field_description': 'node:moduleserver_components:field_description'
  'node:moduleserver_components:field_keys': 'node:moduleserver_components:field_keys'
  'node:moduleserver_components:field_specification': 'node:moduleserver_components:field_specification'
  'node:news:title': 'node:news:title'
  'node:news:body': 'node:news:body'
  'node:page:title': 'node:page:title'
  'node:page:body': 'node:page:body'
  'node:parts:title': 'node:parts:title'
  'node:parts:body': 'node:parts:body'
  'node:platform:title': 'node:platform:title'
  'node:platform:body': 'node:platform:body'
  'node:platform:field_lan_management': 'node:platform:field_lan_management'
  'node:platform:field_lan_ports_speed': 'node:platform:field_lan_ports_speed'
  'node:processor:title': 'node:processor:title'
  'node:processor:body': 'node:processor:body'
  'node:processor:field_processor_number': 'node:processor:field_processor_number'
  'node:processor:field_test': 'node:processor:field_test'
  'node:server:title': 'node:server:title'
  'node:server:field_description': 'node:server:field_description'
  'node:server:field_keys': 'node:server:field_keys'
  'node:server:field_specification': 'node:server:field_specification'
  'node:server:field_test_platform': 'node:server:field_test_platform'
  'node:server:field_test_platform_vendor': 'node:server:field_test_platform_vendor'
  'node:server2:title': 'node:server2:title'
  'node:server2:body': 'node:server2:body'
  'node:server2:field_description': 'node:server2:field_description'
  'node:server2:field_keys': 'node:server2:field_keys'
  'node:server2:field_specification': 'node:server2:field_specification'
  'node:software:title': 'node:software:title'
  'node:software:field_description': 'node:software:field_description'
  'node:software:field_keys': 'node:software:field_keys'
  'node:software:field_specification': 'node:software:field_specification'
  'node:ssdsystem:title': 'node:ssdsystem:title'
  'node:ssdsystem:body': 'node:ssdsystem:body'
  'node:ssdsystem:field_description': 'node:ssdsystem:field_description'
  'node:ssdsystem:field_keys': 'node:ssdsystem:field_keys'
  'node:ssdsystem:field_model': 'node:ssdsystem:field_model'
  'node:ssdsystem:field_specification': 'node:ssdsystem:field_specification'
  'node:superhero_portfolio:title': 'node:superhero_portfolio:title'
  'node:superhero_portfolio:body': 'node:superhero_portfolio:body'
  'node:tis_page:title': 'node:tis_page:title'
  'node:tis_page:body': 'node:tis_page:body'
  'node:vendor_ss:title': 'node:vendor_ss:title'
  'node:vendor_ss:body': 'node:vendor_ss:body'
  'node:webform:title': 'node:webform:title'
  'node:webform:body': 'node:webform:body'
  'paragraph:accordion_item:field_title': 'paragraph:accordion_item:field_title'
  'paragraph:adds:field_add_description': 'paragraph:adds:field_add_description'
  'paragraph:card:field_card_title': 'paragraph:card:field_card_title'
  'paragraph:carousel_item:field_title': 'paragraph:carousel_item:field_title'
  'paragraph:ebt_accordion:field_ebt_accordion_text': 'paragraph:ebt_accordion:field_ebt_accordion_text'
  'paragraph:ebt_accordion:field_ebt_accordion_title': 'paragraph:ebt_accordion:field_ebt_accordion_title'
  'paragraph:ebt_slick_slider:field_ebt_slick_slider_text': 'paragraph:ebt_slick_slider:field_ebt_slick_slider_text'
  'paragraph:ebt_tab:field_ebt_tab_text': 'paragraph:ebt_tab:field_ebt_tab_text'
  'paragraph:ebt_tab:field_ebt_tab_title': 'paragraph:ebt_tab:field_ebt_tab_title'
  'paragraph:paragraphs_pack_content:pp_title': 'paragraph:paragraphs_pack_content:pp_title'
  'paragraph:paragraphs_pack_node_list:pp_title': 'paragraph:paragraphs_pack_node_list:pp_title'
