display:
  default:
    display_title: Default
    display_options:
      fields:
        id:
          label: ID
      exposed_form:
        options:
          reset_button_label: Reset
  list:
    display_title: Page
