display:
  default:
    display_title: Default
    display_options:
      fields:
        id:
          label: ID
        created:
          label: Date
        subject:
          label: Subject
      exposed_form:
        options:
          reset_button_label: Reset
  page_admin_mail_log:
    display_title: Page
